CREATE DATABASE IF NOT EXISTS NOTARIA90;

USE NOTARIA90;

DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE IF NOT EXISTS USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO),
    NOMBRE TEXT NULL,
    CORREO TEXT NULL,
    PASSWORD TEXT NULL
);

DROP TABLE IF EXISTS TRAMITES;
CREATE TABLE IF NOT EXISTS TRAMITES (
    ID_TRAMITE INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_TRAMITES PRIMARY KEY (ID_TRAMITE),
    NOMBRE TEXT NULL
);

DROP TABLE IF EXISTS ESTATUSES;
CREATE TABLE IF NOT EXISTS ESTATUSES (
    ID_ESTATUS INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_ESTATUSES PRIMARY KEY (ID_ESTATUS),
    NOMBRE TEXT NULL
);

DROP TABLE IF EXISTS EXPEDIENTES;
CREATE TABLE IF NOT EXISTS EXPEDIENTES (
    ID_EXPEDIENTE INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_EXPEDIENTES PRIMARY KEY (ID_EXPEDIENTE),
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_EXPEDIENTES_TO_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO),
    ID_TRAMITE INT NOT NULL,
    CONSTRAINT FK_EXPEDIENTES_TO_TRAMITES FOREIGN KEY (ID_TRAMITE) REFERENCES TRAMITES (ID_TRAMITE),
    FECHA DATE NULL,
    ID_ESTATUS INT NOT NULL,
    CONSTRAINT FK_EXPEDIENTES_TO_ESTATUSES FOREIGN KEY (ID_ESTATUS) REFERENCES ESTATUSES (ID_ESTATUS)
);

DROP TABLE IF EXISTS CITAS;
CREATE TABLE IF NOT EXISTS CITAS (
    ID_CITA INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_CITAS PRIMARY KEY (ID_CITA),
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_CITAS_TO_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO),
    NOMBRE TEXT NULL,
    APELLIDO TEXT NULL,
    DIA DATETIME NULL,
);

DROP TABLE IF EXISTS CARTA_PODER;
CREATE TABLE IF NOT EXISTS CARTA_PODER (
    ID_CARTA_PODER INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_CARTA_PODER PRIMARY KEY (ID_CARTA_PODER),
    NOMBRE_PODERANTE TEXT NULL,
    NOMBRE_APODERADO TEXT NULL,
    DOMICILIO TEXT NULL,
    TELEFONO TEXT NULL
);

DROP TABLE IF EXISTS ESTADOS_CIVILES;
CREATE TABLE IF NOT EXISTS ESTADOS_CIVILES (
    ID_ESTADO_CIVIL INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_ESTADOS_CIVILES PRIMARY KEY (ID_ESTADO_CIVIL),
    NOMBRE TEXT NULL
);

DROP TABLE IF EXISTS ESCRITURA_PUBLICA;
CREATE TABLE IF NOT EXISTS ESCRITURA_PUBLICA (
    ID_ESCRITURA_PUBLICA INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_ESCRITURA_PUBLICA PRIMARY KEY (ID_ESCRITURA_PUBLICA),
    NOMBRE TEXT NULL,
    NACIONALIDAD TEXT NULL,
    ID_ESTADO_CIVIL INT NOT NULL,
    CONSTRAINT FK_ESCRITURA_PUBLICA_TO_ESTADOS_CIVILES FOREIGN KEY (ID_ESTADO_CIVIL) REFERENCES ESTADOS_CIVILES (ID_ESTADO_CIVIL),
    OCUPACION TEXT NULL,
    CURP TEXT NULL,
    RFC TEXT NULL
);

DROP TABLE IF EXISTS PAGOS;
CREATE TABLE IF NOT EXISTS PAGOS (
    ID_PAGO INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PAGO),
    NOMBRE TEXT NULL,
    TARJETA TEXT NULL,
    FECHA_DE_VENCIMIENTO TEXT NULL,
    CVV INT NULL,
    MONTO TEXT NULL
);
